version: '3.8'

services:
  app:
    build: .
    container_name: mivo_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app/Database:/var/www/html/app/Database
      - ./.env:/var/www/html/.env
    environment:
      - APP_ENV=production
